name: Deploy Storybook

on:
  push:
    branches: [dev]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Generate Storybook
        run: npm run build-storybook

      - name: Disable Jekyll
        run: touch storybook-static/.nojekyll

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: storybook-static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
